### ISSUE TITLE
Meeting 7/8

### ISSUE THREAD

**Issue by cmodi-umich** [Study-Swap/study-swap-web#30]
## TODO

- [x] Flesh out onboarding process for user/admin more
- [x] Figure out initial issue assignment and sprint management
- [x] Meeting formats (Standups? Sunday spring meetings?)
- [x] Should we start a documentation file/folder on gdrive/notion/something else 
- [x] Fiverr Logo?
